[theme]
primaryColor="#e30613"              # Revolt red
backgroundColor="#f8f9fa"           # Light gray
secondaryBackgroundColor="#ffffff"  # White for cards
textColor="#111111"                 # Dark text
font="sans serif"
