[theme]
primaryColor="#e30613"              # Revolt red (buttons, highlights)
backgroundColor="#f8f9fa"           # Light gray background
secondaryBackgroundColor="#ffffff"  # White cards
textColor="#111111"                 # Dark text
font="sans serif"
