[theme]
primaryColor="#e30613"              # Revolt red
backgroundColor="#f8f9fa"           # Light gray background
secondaryBackgroundColor="#ffffff"  # White card containers
textColor="#111111"                 # Dark text
font="sans serif"
